export type RootStackParamList = {
  Splash: undefined;
  ProLogin: undefined;
  Dashboard: undefined;
  DailyLedger: undefined;
  CustomerLedger: undefined;
  SalesReport: undefined;
  Inventory: undefined;
  Billing: undefined;
  Customers: undefined;
  Suppliers: undefined;
  CashFlow: undefined;
  Reports: undefined;
  TransactionLedger: undefined;
  Deliveries: undefined;
  Employees: undefined;
  GoodsBatch: undefined;
  Influencer: undefined;
  Settings: undefined;
  DailySettlement: undefined;
};
